apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: text2image-deployment
  name: text2image-service
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: text2image-deployment
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: text2image-deployment
  name: text2image-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text2image-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: text2image-deployment
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        image: yahiadev/text2image:0.1.10-SNAPSHOT
        imagePullPolicy: Always
        name: text2image-deployment
        ports:
        - containerPort: 8081
        resources: {}
status: {}
