apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - text2image-api-deployment.yaml
  - text2image-api-service.yaml
  - ingress.yaml


images:
  - name: yahiadev/text2imageapi
    newTag: IMAGE_TAG